### ISSUE TITLE
Translate groups/data.js file

### ISSUE THREAD

**Issue by ellenfang77** [CMU-313/fall23-nodebb-formula1#10]
Issue 1D

- Estimate Effort: 3 days
- Dependencies: None
- Initial Assignments: @kateyzcodes 
- Milestones: Completed in Sprint 1
- Acceptance Criteria:
  - Passes the linter
  - Passes the tests
  - Builds properly

**Comment by vanessalin0226** [comment]
Notes on files to touch:

- **Group page**
  - themes/nodebb-theme-persona/templates/partials/groups/list.tpl
  - Outside of each group
  - Within group the member display area
- **User page**
  - themes/nodebb-theme-persona/templates/partials/users_list.tpl
