### ISSUE TITLE
Design Interface + Connect Number of Online Counts

### ISSUE THREAD

**Issue by ellenfang77** [CMU-313/fall23-nodebb-formula1#9]
Issue 1C

- Estimated Effort: 5 days
- Dependencies: none
- Initial Assignments: @vanessalin0226 
- Milestones: Completed in Sprint 1
- Acceptance Criteria:
  - Displays correct online counts on UI at right places

**Comment by vanessalin0226** [comment]
Hello

**Comment by vanessalin0226** [comment]
Notes on files to touch:

- **Group page**
  - themes/nodebb-theme-persona/templates/partials/groups/list.tpl
  - Outside of each group
  - Within group the member display area
- **User page**
  - themes/nodebb-theme-persona/templates/partials/users_list.tpl
  - themes/nodebb-theme-persona/templates/partials/users_list_menu.tpl
